/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CredentialAnchor__factory } from "./CredentialAnchor__factory";
export { IssuerRegistry__factory } from "./IssuerRegistry__factory";
