/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CredentialAnchorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchorCredential"
      | "batchAnchorCredentials"
      | "credentials"
      | "registry"
      | "revokeCredential"
      | "verifyCredential"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CredentialAnchored" | "CredentialRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorCredential",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchAnchorCredentials",
    values: [string[], BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "credentials", values: [string]): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCredential",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "anchorCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchAnchorCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "credentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCredential",
    data: BytesLike
  ): Result;
}

export namespace CredentialAnchoredEvent {
  export type InputTuple = [
    refId: string,
    issuer: AddressLike,
    dataHash: BytesLike
  ];
  export type OutputTuple = [refId: string, issuer: string, dataHash: string];
  export interface OutputObject {
    refId: string;
    issuer: string;
    dataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [refId: string, issuer: AddressLike];
  export type OutputTuple = [refId: string, issuer: string];
  export interface OutputObject {
    refId: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CredentialAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): CredentialAnchor;
  waitForDeployment(): Promise<this>;

  interface: CredentialAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorCredential: TypedContractMethod<
    [refId: string, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  batchAnchorCredentials: TypedContractMethod<
    [refIds: string[], dataHashes: BytesLike[]],
    [void],
    "nonpayable"
  >;

  credentials: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        dataHash: string;
        issuer: string;
        issuedAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  revokeCredential: TypedContractMethod<[refId: string], [void], "nonpayable">;

  verifyCredential: TypedContractMethod<
    [refId: string, dataHash: BytesLike],
    [
      [boolean, boolean, string] & {
        valid: boolean;
        revoked: boolean;
        issuer: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorCredential"
  ): TypedContractMethod<
    [refId: string, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchAnchorCredentials"
  ): TypedContractMethod<
    [refIds: string[], dataHashes: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "credentials"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        dataHash: string;
        issuer: string;
        issuedAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeCredential"
  ): TypedContractMethod<[refId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyCredential"
  ): TypedContractMethod<
    [refId: string, dataHash: BytesLike],
    [
      [boolean, boolean, string] & {
        valid: boolean;
        revoked: boolean;
        issuer: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CredentialAnchored"
  ): TypedContractEvent<
    CredentialAnchoredEvent.InputTuple,
    CredentialAnchoredEvent.OutputTuple,
    CredentialAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;

  filters: {
    "CredentialAnchored(string,address,bytes32)": TypedContractEvent<
      CredentialAnchoredEvent.InputTuple,
      CredentialAnchoredEvent.OutputTuple,
      CredentialAnchoredEvent.OutputObject
    >;
    CredentialAnchored: TypedContractEvent<
      CredentialAnchoredEvent.InputTuple,
      CredentialAnchoredEvent.OutputTuple,
      CredentialAnchoredEvent.OutputObject
    >;

    "CredentialRevoked(string,address)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
  };
}
